#pragma once

#define TANMATSU_EVENT_LORA      0x01
#define TANMATSU_EVENT_BADGELINK 0x02
#define TANMATSU_EVENT_ECHO      0x03
#define TANMATSU_EVENT_IR        0x04
#define TANMATSU_EVENT_AIRPLANE  0x05
